# Generated by Django 4.2.1 on 2023-12-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_type_product_typee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='typee',
            new_name='type',
        ),
    ]
